### ISSUE TITLE
Solargraph formatting doesn't follow the project's .rubocop.yml file

### ISSUE THREAD

**Issue by guilhermedeandrade** [castwide/vscode-solargraph#206]
Solargraph formatting doesn't follow the project's `.rubocop.yml` file.

Here is my `.solargraph.yml` file:

```yaml
---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".bundle/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
require_paths: []
plugins: []
max_files: 5000
```

And here is a part of `settings.json`:

```json
{
 ...
  "solargraph.diagnostics": true,
  "solargraph.hover": true,
  "solargraph.formatting": true
}
```

Example file:

```rb
class Cat
  def meow
    'meow!'
  end
end
```

Even though `.rubocop.yml` contains the following cop:
```yaml
Style/StringLiterals:
  EnforcedStyle: double_quotes
```

Solargraph won't format the `'meow!'` to `"meow"!`. This is just an example, the same thing happens with others cops.

Also, somehow, if I do write the class like this:
```rb
class Cat
  def meow
    "meow!"
  end
end
```

The Solargraph formatter will "work" and replace the double quotes for single quotes.
