### ISSUE TITLE
Solargraph gets stuck when saving file

### ISSUE THREAD

**Issue by ruggieroguida** [castwide/vscode-solargraph#234]
```
OS: Bigsur
vscode version: 1.62.2
Ruby 2.7.1 (with rbenv)
solargraph version: 0.44.0
extension version: v0.23.0
```

All of a sudden solargraph has stopped working. It is not allowing me to save any file and it gets stuck at 
```
"Saving 'anyfile.rb': Running 'Ruby Solargraph' Formatter (configure)."
```

The only way to proceed is to click cancel. I literally cannot save any file. It has been working fine for years.

This is the content of `.solargraph.yml`. No change from the default one
```
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
```

Any suggestion?
