### ISSUE TITLE
How to debug - An error occurred while building gem documentation

### ISSUE THREAD

**Issue by mioruggieroguida** [castwide/vscode-solargraph#275]
When i rebuild the gems documentation, i keep getting this message.

`An error occurred while building gem documentation`

Is there a log where I can get more info?

this is my `.solargraph.yml`

```
---
include:
  - "**/*.rb"
exclude:
  - spec/**/*
  - vendor/**/*
  - ".bundle/**/*"
require:
 - openstudio-standards
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: ["."]
plugins: []
max_files: 5000
```
