### ISSUE TITLE
Excluded RuboCop rules still show up in VSCode?

### ISSUE THREAD

**Issue by thomthom** [castwide/vscode-solargraph#57]
I see RuboCop warnings in the IDE for things that are disabled by the `.rubocop.yml` file. (In this case `.rubocop_todo.yml`:

```yml
# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, IgnoreClassMethods, Whitelist.
# Whitelist: to_ary, to_a, to_c, to_enum, to_h, to_hash, to_i, to_int, to_io, to_open, to_path, to_proc, to_r, to_regexp, to_str, to_s, to_sym
Style/TrivialAccessors:
  Exclude:
    - 'src/tt_truebend/bender.rb'
```

![image](https://user-images.githubusercontent.com/192418/40734659-58256a7c-6439-11e8-9dd6-f67699313b35.png)

But strangely enough, another setting do seem to work:

```yml
# Offense count: 8
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 99
```

Anyone run into this?

When I run rubocop from the console there are warnings.

(RuboCop 0.54, Solargraph 0.22, VSCode extension 0.17.4)
