### ISSUE TITLE
[Errno::ENOENT] No such file or directory @ realpath_rec 

### ISSUE THREAD

**Issue by maqen** [castwide/vscode-solargraph#62]
I'm getting following startup error tying to use the extension

`[Errno::ENOENT] No such file or directory @ realpath_rec - /Users/max/workspace/project/vendor
/ruby/2.5.0/gems/rubycritic-3.4.0/test/samples/location/test`

Is this an error with my configuration or a plugin exception?

I've tried to rebundle and reinstall the extension but still same error

I see that that folder is not present in `rubycritic` gem but that test folder/files is not there? https://github.com/whitesmith/rubycritic/tree/v3.4.0/test/samples/location

My `.solargraph.yml` file

```yaml
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters: []
plugins: []
max_files: 5000
```

My bundle gems are installed in `./vendor`
