### ISSUE TITLE
`exclude:` config has no effect

### ISSUE THREAD

**Issue by dogweather** [castwide/vscode-solargraph#93]
In VS Code, when I open an rspec file, it's covered by an `exclude:` in my `.solargraph.yml`. However, Solargraph lints it anyhow. 

My config:

```yaml
---
include:
- "**/*.rb"
exclude:
- spec/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
plugins: []
require_paths: []
max_files: 5000
```

Ruby 2.6.0
Solargraph 0.30.1
VS Code 1.30.1
